# Default values for fec-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

manager:
  image:
    repository: docker.io/starlingx/sriov-fec-operator
    tag: stx.8.0-v2.1.1-1

kubeRbacProxy:
  name: kube-rbac-proxy
  image:
    repository: gcr.io/kubebuilder/kube-rbac-proxy
    tag: v0.11.0

env:
  SRIOV_FEC_IMAGE_PULL_SECRET: "default-registry-key"
  SRIOV_FEC_DAEMON_IMAGE: "registry.local:9001/docker.io/starlingx/sriov-fec-daemon:stx.8.0-v2.1.1-1"
  SRIOV_FEC_LABELER_IMAGE: "registry.local:9001/docker.io/starlingx/sriov-fec-labeler:stx.8.0-v2.1.1-1"
  SRIOV_FEC_NETWORK_DEVICE_PLUGIN_IMAGE: "registry.local:9001/ghcr.io/k8snetworkplumbingwg/sriov-network-device-plugin:v3.5.1"
  KUBE_RBAC_PROXY_IMAGE: "registry.local:9001/gcr.io/kubebuilder/kube-rbac-proxy:v0.11.0"
