---
- project:
    check:
      jobs:
        - openstack-tox-linters
        - k8sapp-sriov-fec-operator-tox-py39
        - k8sapp-sriov-fec-operator-tox-pylint
    gate:
      jobs:
        - openstack-tox-linters
        - k8sapp-sriov-fec-operator-tox-py39
        - k8sapp-sriov-fec-operator-tox-pylint

- job:
    name: k8sapp-sriov-fec-operator-tox-py39
    parent: tox-py39
    description: |
        Run py39 for sriov-fec-operator app
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/update
      - starlingx/utilities
    files:
      - python3-k8sapp-sriov-fec-operator/*
    vars:
        tox_envlist: py39
        python_version: 3.9
        tox_extra_args: -c python3-k8sapp-sriov-fec-operator/k8sapp_sriov_fec_operator/tox.ini

- job:
    name: k8sapp-sriov-fec-operator-tox-pylint
    parent: tox
    description: |
      Run pylint test for k8sapp_sriov_fec_operator
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/update
      - starlingx/utilities
    nodeset: debian-bullseye
    files:
      - python3-k8sapp-sriov-fec-operator/*
    vars:
      tox_envlist: pylint
      tox_extra_args: -c python3-k8sapp-sriov-fec-operator/k8sapp_sriov_fec_operator/tox.ini
