apiVersion: v1
data:
  controller_manager_config.yaml: |
    # SPDX-License-Identifier: Apache-2.0
    # Copyright (c) 2022-2025 Intel Corporation

    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: bab0ab5c.intel.com
kind: ConfigMap
metadata:
  name: sriov-fec-manager-config
  namespace: sriov-fec-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: sriov-fec-system
  name: operator-configuration
data:
  isGeneric: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sriov-fec-daemon-assets
  namespace: sriov-fec-system
immutable: false
data:
  daemon-assets.yaml: |
    # SPDX-License-Identifier: Apache-2.0
    # Copyright (c) 2020-2025 Intel Corporation

    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: daemon-config
      namespace: "{{.Values.env.SRIOV_FEC_NAMESPACE}}"
    immutable: false
    data:
      serviceAccount: |
        apiVersion: v1
        kind: ServiceAccount
        imagePullSecrets:
          - name: "{{.Values.env.SRIOV_FEC_IMAGE_PULL_SECRET}}"
        metadata:
          name: sriov-fec-daemon
          namespace: "{{.Values.env.SRIOV_FEC_NAMESPACE}}"
      role: |
        apiVersion: rbac.authorization.k8s.io/v1
        kind: Role
        metadata:
          name: sriov-fec-daemon
          namespace: "{{.Values.env.SRIOV_FEC_NAMESPACE}}"
        rules:
        - apiGroups:
          - sriovfec.intel.com
          resources:
          - sriovfecclusterconfigs
          - sriovfecnodeconfigs
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - sriovfec.intel.com
          resources:
          - sriovfecclusterconfigs/status
          - sriovfecnodeconfigs/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - sriovvrb.intel.com
          resources:
          - sriovvrbclusterconfigs
          - sriovvrbnodeconfigs
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - sriovvrb.intel.com
          resources:
          - sriovvrbclusterconfigs/status
          - sriovvrbnodeconfigs/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - security.openshift.io
          resources:
          - securitycontextconstraints
          verbs:
          - use
          resourceNames:
          - privileged
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups: [""]
          resources: ["configmaps"]
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
      roleBinding: |
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: sriov-fec-daemon
          namespace: "{{.Values.env.SRIOV_FEC_NAMESPACE}}"
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: Role
          name: sriov-fec-daemon
        subjects:
        - kind: ServiceAccount
          name: sriov-fec-daemon
          namespace: "{{.Values.env.SRIOV_FEC_NAMESPACE}}"
      clusterRole: |
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        metadata:
          name: sriov-fec-daemon
        rules:
        - apiGroups: [""]
          resources: ["pods"]
          verbs: ["get","list","watch","create","update", "patch", "delete"]
        - apiGroups: [""]
          resources: ["nodes"]
          verbs: ["get", "list", "watch", "patch", "update"]
        - apiGroups: ["apps"]
          resources: ["daemonsets"]
          verbs: ["get"]
        - apiGroups: [""]
          resources: ["pods/eviction"]
          verbs: ["create"]
      clusterRoleBinding: |
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: sriov-fec-daemon
        subjects:
        - kind: ServiceAccount
          name: sriov-fec-daemon
          namespace: "{{.Values.env.SRIOV_FEC_NAMESPACE}}"
        roleRef:
          kind: ClusterRole
          name: sriov-fec-daemon
          apiGroup: rbac.authorization.k8s.io
          namespace: "{{.Values.env.SRIOV_FEC_NAMESPACE}}"
      secret: |
        apiVersion: v1
        kind: Secret
        metadata:
          name: vfio-token
          namespace: "{{.Values.env.SRIOV_FEC_NAMESPACE}}"
        type: Opaque
        stringData:
          VFIO_TOKEN: {{.Values.env.SRIOV_FEC_VFIO_TOKEN | default "02bddbbf-bbb0-4d79-886b-91bad3fbb510" | quote }}
        immutable: true
      daemonSet: |
        apiVersion: apps/v1
        kind: DaemonSet
        metadata:
          labels:
            app: sriov-fec-daemonset
          name: sriov-fec-daemonset
          namespace: "{{.Values.env.SRIOV_FEC_NAMESPACE}}"
          annotations:
            openshift.io/scc: sriov-fec-daemon
        spec:
          selector:
            matchLabels:
              app: sriov-fec-daemonset
          template:
            metadata:
              # Mark this pod as a critical add-on; when enabled, the critical add-on scheduler
              # reserves resources for critical add-on pods so that they can be rescheduled after
              # a failure.  This annotation works in tandem with the toleration below.
              annotations:
                scheduler.alpha.kubernetes.io/critical-pod: ""
              labels:
                app: sriov-fec-daemonset
            spec:
              nodeSelector:
                fpga.intel.com/intel-accelerator-present: ""
              shareProcessNamespace: true
              tolerations:
              - key: intel.com/sriovfec
                operator: Exists
                effect: NoSchedule
              serviceAccount: sriov-fec-daemon
              serviceAccountName: sriov-fec-daemon
              hostPID: false
              hostNetwork: false
              dnsPolicy: Default
              containers:
              - name: sriov-fec-daemon
                image: "{{.Values.env.SRIOV_FEC_DAEMON_IMAGE}}"
                imagePullPolicy: IfNotPresent
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: {{.Values.env.SRIOV_FEC_DAEMON_LIVENESS_INITIAL_DELAY_SECONDS}}
                  periodSeconds: {{.Values.env.SRIOV_FEC_DAEMON_LIVENESS_PERIOD_SECONDS}}
                  failureThreshold: {{.Values.env.SRIOV_FEC_DAEMON_LIVENESS_FAILURE_THRESHOLD}}
                  successThreshold: {{.Values.env.SRIOV_FEC_DAEMON_LIVENESS_SUCCESS_THRESHOLD}}
                  timeoutSeconds: {{.Values.env.SRIOV_FEC_DAEMON_LIVENESS_TIMEOUT_SECONDS}}
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: {{.Values.env.SRIOV_FEC_DAEMON_READINESS_INITIAL_DELAY_SECONDS}}
                  periodSeconds: {{.Values.env.SRIOV_FEC_DAEMON_READINESS_PERIOD_SECONDS}}
                  failureThreshold: {{.Values.env.SRIOV_FEC_DAEMON_READINESS_FAILURE_THRESHOLD}}
                  successThreshold: {{.Values.env.SRIOV_FEC_DAEMON_READINESS_SUCCESS_THRESHOLD}}
                  timeoutSeconds: {{.Values.env.SRIOV_FEC_DAEMON_READINESS_TIMEOUT_SECONDS}}
                ports:
                - containerPort: 8080
                  name: bbdevconfig
                volumeMounts:
                - name: tlscert
                  mountPath: "/etc/certificate"
                  readOnly: true
                - name: devvfio
                  mountPath: /dev/vfio
                  readOnly: true
                - name: vfiotoken
                  mountPath: /sriov_config/
                  readOnly: true
                - name: libmodules
                  mountPath: /lib/modules
                  readOnly: true
                - mountPath: /sriov_config/config
                  name: config-volume
                  readOnly: true
                - name: logs
                  mountPath: /var/log
                - name: tmp
                  mountPath: /tmp
                - name: lockdown
                  mountPath: /sys/kernel/security
                  readOnly: true
                - name: sys
                  mountPath: /sys
                env:
                  - name: SRIOV_FEC_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  - name: NODENAME
                    valueFrom:
                      fieldRef:
                        fieldPath: spec.nodeName
                  - name: DRAIN_TIMEOUT_SECONDS
                    value: "90"
                  - name: LEASE_DURATION_SECONDS
                    value: "600"
                  - name: SRIOV_FEC_METRIC_GATHER_INTERVAL
                    value: "{{.Values.env.SRIOV_FEC_METRIC_GATHER_INTERVAL}}"
                  - name: GHW_DISABLE_WARNINGS
                    value: "1"
                securityContext:
                  readOnlyRootFilesystem: true
                  privileged: true
                  runAsUser: 0
                  capabilities:
                    add:
                      - "ALL"
              volumes:
              - name: tlscert
                secret:
                  secretName: tls-cert
                  optional: true
              - configMap:
                  defaultMode: 420
                  items:
                  - key: accelerators.json
                    path: accelerators.json
                  - key: accelerators_vrb.json
                    path: accelerators_vrb.json
                  name: supported-accelerators
                name: config-volume
              - name: vfiotoken
                secret:
                  secretName: vfio-token
                  optional: false
                  items:
                  - key: VFIO_TOKEN
                    path: vfiotoken
              - name: devvfio
                hostPath:
                  path: /dev/vfio
              - name: libmodules
                hostPath:
                  path: /lib/modules
              - name: logs
                emptyDir: {}
              - name: tmp
                emptyDir: {}
              - name: lockdown
                hostPath:
                  path: /sys/kernel/security
              - name: sys
                hostPath:
                  path: /sys
