# Default values for fec-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

manager:
  image:
    repository: docker.io/starlingx/sriov-fec-operator
    tag: stx.12.0-v2.12.0

kubeRbacProxy:
  name: kube-rbac-proxy
  image:
    repository: registry.k8s.io/kubebuilder/kube-rbac-proxy
    tag: v0.15.0

env:
  SRIOV_FEC_NAMESPACE: "sriov-fec-system"
  SRIOV_FEC_LTE_RESOURCE_NAME: ""
  SRIOV_FEC_5G_RESOURCE_NAME: ""
  SRIOV_FEC_ACC100_RESOURCE_NAME: ""
  SRIOV_FEC_ACC200_RESOURCE_NAME: ""
  SRIOV_FEC_VFIO_TOKEN: ""
  SRIOV_FEC_IMAGE_PULL_SECRET: "default-registry-key"
  SRIOV_FEC_DAEMON_IMAGE: "registry.local:9001/docker.io/starlingx/sriov-fec-daemon:stx.12.0-v2.12.0"
  SRIOV_FEC_DAEMON_LIVENESS_INITIAL_DELAY_SECONDS: "15"
  SRIOV_FEC_DAEMON_LIVENESS_PERIOD_SECONDS: "20"
  SRIOV_FEC_DAEMON_LIVENESS_FAILURE_THRESHOLD: "3"
  SRIOV_FEC_DAEMON_LIVENESS_SUCCESS_THRESHOLD: "1"
  SRIOV_FEC_DAEMON_LIVENESS_TIMEOUT_SECONDS: "5"
  SRIOV_FEC_DAEMON_READINESS_INITIAL_DELAY_SECONDS: "5"
  SRIOV_FEC_DAEMON_READINESS_PERIOD_SECONDS: "10"
  SRIOV_FEC_DAEMON_READINESS_FAILURE_THRESHOLD: "3"
  SRIOV_FEC_DAEMON_READINESS_SUCCESS_THRESHOLD: "1"
  SRIOV_FEC_DAEMON_READINESS_TIMEOUT_SECONDS: "5"
  SRIOV_FEC_MANAGER_LIVENESS_INITIAL_DELAY_SECONDS: "15"
  SRIOV_FEC_MANAGER_LIVENESS_PERIOD_SECONDS: "20"
  SRIOV_FEC_MANAGER_LIVENESS_FAILURE_THRESHOLD: "3"
  SRIOV_FEC_MANAGER_LIVENESS_SUCCESS_THRESHOLD: "1"
  SRIOV_FEC_MANAGER_LIVENESS_TIMEOUT_SECONDS: "5"
  SRIOV_FEC_MANAGER_READINESS_INITIAL_DELAY_SECONDS: "5"
  SRIOV_FEC_MANAGER_READINESS_PERIOD_SECONDS: "10"
  SRIOV_FEC_MANAGER_READINESS_FAILURE_THRESHOLD: "3"
  SRIOV_FEC_MANAGER_READINESS_SUCCESS_THRESHOLD: "1"
  SRIOV_FEC_MANAGER_READINESS_TIMEOUT_SECONDS: "5"
  SRIOV_FEC_METRIC_GATHER_INTERVAL: "0s"
  SRIOV_FEC_LABELER_IMAGE: "registry.local:9001/docker.io/starlingx/sriov-fec-labeler:stx.12.0-v2.12.0"
  SRIOV_FEC_NETWORK_DEVICE_PLUGIN_IMAGE: "registry.local:9001/ghcr.io/k8snetworkplumbingwg/sriov-network-device-plugin:v3.7.0"
  KUBE_RBAC_PROXY_IMAGE: "registry.local:9001/registry.k8s.io/kubebuilder/kube-rbac-proxy:v0.15.0"
